CREATE TABLE IF NOT EXISTS `contacts` (
  `contact_id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `client_id` int(10) unsigned DEFAULT NULL,
  `staff_id` int(10) unsigned DEFAULT NULL,
  `first_name` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `last_name` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `email` varchar(255) COLLATE ascii_bin NOT NULL,
  `contact_password` varchar(60) COLLATE ascii_bin NOT NULL,
  `contact_type` enum('bill','ship','both') COLLATE ascii_bin NOT NULL DEFAULT 'both',
  `contact_is_active` tinyint(1) NOT NULL,
  `contact_last_login` int(10) NOT NULL,
  `contact_created` int(10) NOT NULL,
  `contact_updated` int(10) NOT NULL,
  `phone` varchar(255) COLLATE ascii_bin NOT NULL,
  `fax` varchar(255) COLLATE ascii_bin DEFAULT NULL,
  `address_name` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `address_1` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `address_2` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `city` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `state` char(2) COLLATE ascii_bin NOT NULL,
  `zip` varchar(20) COLLATE ascii_bin NOT NULL,
  `country` char(2) COLLATE ascii_bin NOT NULL,
  PRIMARY KEY (`contact_id`),
  KEY `staff_id` (`staff_id`),
  KEY `client_id` (`client_id`)
) ENGINE=MyISAM DEFAULT CHARSET=ascii COLLATE=ascii_bin AUTO_INCREMENT=1 ;
